#server:
#  port: 8090
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/whalewarehouse
#    username: postgres
#    password: password
#    driverClassName: org.postgresql.Driver
#  jpa:
#    show-sql: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

