#server:
#  port: 8090
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/whalewarehouse
#    username: postgres
#    password: password
#    driverClassName: org.postgresql.Driver
#  jpa:
#    show-sql: true
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true