server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whale-warehouse-postgres
    username: DB_USER
    password: DB_PASSWORD
    driverClassName: org.postgresql.Driver
