version: '3.17'
services:
  postgres-db:
    container_name: whale-warehouse-postgres
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whalewarehouse